version: '3.7'

services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - /var/lib/postgresql/data
      - ./movies.sql:/docker-entrypoint-initdb.d/movies.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgresdb

# volumes:
  # postgres_data:
